# Generated by Django 5.0.1 on 2024-01-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Poroda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opisanie')),
            ],
            options={
                'verbose_name': 'poroda',
                'verbose_name_plural': 'porody',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Klichka')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Foto')),
                ('birth_day', models.DateTimeField(blank=True, null=True, verbose_name='Data Rozhdenie')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Poroda')),
            ],
            options={
                'verbose_name': 'sobaka',
                'verbose_name_plural': 'sobaki',
            },
        ),
    ]
