# Generated by Django 5.0.1 on 2024-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
